/*
* Generated file
*
* Generated from: yang module name: python-engine-impl yang module local name: python-engine-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon May 16 17:47:02 BST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.python_engine.impl;
public interface PythonEngineModuleMXBean {
    public javax.management.ObjectName getBindingAwareBroker();

    public void setBindingAwareBroker(javax.management.ObjectName bindingAwareBroker);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getSchemaService();

    public void setSchemaService(javax.management.ObjectName schemaService);

    public javax.management.ObjectName getDomDataBroker();

    public void setDomDataBroker(javax.management.ObjectName domDataBroker);

}
