/*
* Generated file
*
* Generated from: yang module name: python-engine-impl yang module local name: python-engine-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon May 16 17:43:29 BST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.python_engine.impl;
public class PythonEngineModuleFactory extends org.opendaylight.controller.config.yang.config.python_engine.impl.AbstractPythonEngineModuleFactory {

}
